Refactor Need to fix error
+ python3 PreProcess.py Test-corpus/AS/ASD.xml Test-corpus/AS/ASD.pre.txt
Traceback (most recent call last):
  File "PreProcess.py", line 23, in <module>
    main()
  File "PreProcess.py", line 15, in main
    text=element.text.strip()
AttributeError: 'NoneType' object has no attribute 'strip'

Signed-off-by: sunnysideup <kssuraaj28@gmail.com>